name : fullstack-demo
services:
  front : 
    container_name : front-container
    build : 
      context : ./frontend
      dockerfile : Dockerfile
    image : front-image
    ports : 
      - "80:80"
    networks :
      - my-net
  back : 
    container_name : back-container
    build : 
      context : ./backend
      dockerfile : Dockerfile
    image : back-image
    ports : 
      - "5000:5000"
    networks :
      - my-net

networks:
  my-net:
    